image: alpine:latest

html:
  image: ${CI_REGISTRY}/woowoo/woowoo:latest
  stage: build
  script:
    - ruby -v                  # print ruby version
    - woo -v                   # print woo version
    - pandoc -v                # print pandoc version
    - pdflatex -v              # print pdflatex version
    - pygmentize -V            # print pygmentize version
    - cd src
    # - cp -r /opt/woowoo/templates ./
    - woo list                 # check available templates, to be sure
    - rake fikshtml:assets fikshtml:build
    - tar -czvf build/tutorials-pages.tar.gz build/fiks-html
    - mv build/tutorials-pages.tar.gz build/fit-html
  artifacts:
    expire_in: 2 hours
    paths:
      - src/build/fit-html


# Deploy to FIT Pages


pages:
  stage: deploy
  tags: [linux, shared]
  script:
    - mkdir public
    - cp -r src/build/fiks-html/* public/
    # - cp src/build/fit-pdf/tutorials*.pdf public/
    - cp .fit-pages.yml public/
  dependencies:
    - html
    - pdf
  artifacts:
    paths:
      - public/
    expire_in: 2 hours
